import json

import numpy as np
import pytest

import rank_products as rp


# ============================================================
# Helpers
# ============================================================

def fake_encode_text(text):
    """
    Fake query embedding.

    Dimension is intentionally small so the test
    does not call Hugging Face.
    """

    return [
        1.0,
        0.0,
        0.0,
    ]


def make_fake_products(candidates):
    """
    Build fake product embeddings using the REAL
    product IDs found in style_kb_matched.jsonl.
    """

    products = {}

    # --------------------------------------------------------
    # Top
    # --------------------------------------------------------

    top_vectors = [
        [1.0, 0.0, 0.0],
        [0.8, 0.6, 0.0],
        [0.6, 0.8, 0.0],
    ]

    for i, candidate in enumerate(
        candidates["top"]
    ):
        vector = top_vectors[
            i % len(top_vectors)
        ]

        products[
            candidate["product_id"]
        ] = {
            "product_id":
                candidate["product_id"],

            "category":
                "top",

            "embedding":
                rp.normalize_embedding(
                    vector
                ),
        }

    # --------------------------------------------------------
    # Bottom
    # --------------------------------------------------------

    bottom_vectors = [
        [1.0, 0.0, 0.0],
        [0.9, 0.1, 0.0],
        [0.7, 0.3, 0.0],
    ]

    for i, candidate in enumerate(
        candidates["bottom"]
    ):
        vector = bottom_vectors[
            i % len(bottom_vectors)
        ]

        products[
            candidate["product_id"]
        ] = {
            "product_id":
                candidate["product_id"],

            "category":
                "bottom",

            "embedding":
                rp.normalize_embedding(
                    vector
                ),
        }

    return products


# ============================================================
# Test 1
# Real style_kb_matched.jsonl can be loaded
# ============================================================

def test_load_real_style_candidates():

    candidates = (
        rp.load_style_candidates(
            "old_money"
        )
    )

    assert "top" in candidates
    assert "bottom" in candidates

    assert len(
        candidates["top"]
    ) > 0

    assert len(
        candidates["bottom"]
    ) > 0

    # build_style_lookup.py currently keeps Top-10.
    assert len(
        candidates["top"]
    ) <= 10

    assert len(
        candidates["bottom"]
    ) <= 10

    # Check structure generated by stage 1.
    for candidate in (
        candidates["top"]
        + candidates["bottom"]
    ):

        assert "product_id" in candidate
        assert "score" in candidate

        assert isinstance(
            candidate["score"],
            (int, float),
        )


# ============================================================
# Test 2
# Embedding normalization
# ============================================================

def test_normalize_embedding():

    embedding = (
        rp.normalize_embedding(
            [3.0, 4.0, 0.0]
        )
    )

    assert np.isclose(
        np.linalg.norm(
            embedding
        ),
        1.0,
    )

    assert np.allclose(
        embedding,
        [
            0.6,
            0.8,
            0.0,
        ],
    )


# ============================================================
# Test 3
# PostgreSQL-style string embedding
# ============================================================

def test_normalize_string_embedding():

    embedding = (
        rp.normalize_embedding(
            "[3.0, 4.0, 0.0]"
        )
    )

    assert np.allclose(
        embedding,
        [
            0.6,
            0.8,
            0.0,
        ],
    )


# ============================================================
# Test 4
# User score = average cosine similarity
# ============================================================

def test_calculate_user_score():

    product_embedding = (
        rp.normalize_embedding(
            [1.0, 0.0, 0.0]
        )
    )

    user_embeddings = [
        rp.normalize_embedding(
            [1.0, 0.0, 0.0]
        ),
        rp.normalize_embedding(
            [0.0, 1.0, 0.0]
        ),
    ]

    score = (
        rp.calculate_user_score(
            product_embedding,
            user_embeddings,
        )
    )

    # Similarities:
    #
    # 1.0
    # 0.0
    #
    # average = 0.5

    assert np.isclose(
        score,
        0.5,
    )


# ============================================================
# Test 5
# No user history
# ============================================================

def test_no_user_history():

    product_embedding = (
        rp.normalize_embedding(
            [1.0, 0.0, 0.0]
        )
    )

    score = (
        rp.calculate_user_score(
            product_embedding,
            [],
        )
    )

    assert score is None


# ============================================================
# Test 6
# Final weighted score
# ============================================================

def test_final_score():

    user_score = 0.8
    query_score = 0.5

    score = (
        rp.calculate_final_score(
            user_score,
            query_score,
        )
    )

    expected = (
        rp.USER_WEIGHT
        * user_score
        +
        rp.QUERY_WEIGHT
        * query_score
    )

    assert np.isclose(
        score,
        expected,
    )


# ============================================================
# Test 7
# Without user history -> query only
# ============================================================

def test_final_score_without_user():

    query_score = 0.73

    score = (
        rp.calculate_final_score(
            None,
            query_score,
        )
    )

    assert np.isclose(
        score,
        query_score,
    )


# ============================================================
# Test 8
# Rank real Stage-1 candidates
# ============================================================

def test_rank_real_style_candidates():

    # REAL candidates generated by
    # build_style_lookup.py.
    candidates = (
        rp.load_style_candidates(
            "old_money"
        )
    )

    # Fake embeddings, but using the REAL product IDs.
    products = (
        make_fake_products(
            candidates
        )
    )

    query_embedding = (
        rp.normalize_embedding(
            [1.0, 0.0, 0.0]
        )
    )

    user_embeddings = [
        rp.normalize_embedding(
            [1.0, 0.0, 0.0]
        )
    ]

    results = (
        rp.rank_category(
            candidates=
                candidates["top"],

            products=
                products,

            user_embeddings=
                user_embeddings,

            query_embedding=
                query_embedding,

            top_m=3,
        )
    )

    assert len(results) == 3

    # Scores must be descending.
    final_scores = [
        item["final_score"]
        for item in results
    ]

    assert final_scores == sorted(
        final_scores,
        reverse=True,
    )

    # Output structure.
    for result in results:

        assert "product_id" in result
        assert "style_score" in result
        assert "user_score" in result
        assert "query_score" in result
        assert "final_score" in result


# ============================================================
# Test 9
# Full pipeline
# ============================================================

def test_full_ranking_pipeline(
    monkeypatch,
):

    # --------------------------------------------------------
    # Read REAL Stage-1 output
    # --------------------------------------------------------

    candidates = (
        rp.load_style_candidates(
            "old_money"
        )
    )

    fake_products = (
        make_fake_products(
            candidates
        )
    )

    # --------------------------------------------------------
    # Mock Hugging Face
    # --------------------------------------------------------

    monkeypatch.setattr(
        rp,
        "encode_text",
        fake_encode_text,
    )

    # --------------------------------------------------------
    # Mock product DB
    # --------------------------------------------------------

    monkeypatch.setattr(
        rp,
        "load_candidate_products",
        lambda product_ids:
            fake_products,
    )

    # --------------------------------------------------------
    # Mock user preference DB
    # --------------------------------------------------------

    def fake_user_preferences(
        user_id,
        category,
    ):

        if category == "top":

            return [
                rp.normalize_embedding(
                    [1.0, 0.0, 0.0]
                )
            ]

        return [
            rp.normalize_embedding(
                [0.9, 0.1, 0.0]
            )
        ]

    monkeypatch.setattr(
        rp,
        "load_user_preference_embeddings",
        fake_user_preferences,
    )

    # --------------------------------------------------------
    # Run COMPLETE second stage
    # --------------------------------------------------------

    result = rp.rank_products(
        user_id="test_user",

        style_name="old_money",

        query_text=(
            "A clean and slightly formal "
            "outfit for warm weather."
        ),

        top_m=3,
    )

    # --------------------------------------------------------
    # Verify final output
    # --------------------------------------------------------

    assert result[
        "user_id"
    ] == "test_user"

    assert result[
        "style"
    ] == "old_money"

    assert len(
        result["top"]
    ) == 3

    assert len(
        result["bottom"]
    ) == 3

    # Check final ranking.
    for category in [
        "top",
        "bottom",
    ]:

        scores = [
            item["final_score"]
            for item
            in result[category]
        ]

        assert scores == sorted(
            scores,
            reverse=True,
        )